windsurf.locations.source-name=locations.json
windsurf.forecast.executor.pool-size=5
windsurf.forecast.cache.ttl-in-hours=12
windsurf.weatherbit.base-url=https://api.weatherbit.io
windsurf.weatherbit.api-key=${WEATHERBIT_API_KEY}
windsurf.weatherbit.forecast-days=7
windsurf.weatherbit.forecast-path=/v2.0/forecast/daily

logging.level.com.pretz.windsurf=DEBUG
